name: 'Bring Env Up & Down'

on:
  workflow_dispatch :
    inputs :
      Capacity:
        description: 'Desired capacity'
        required: true        

jobs:
  build:
    name: Refresh environment 
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Web
      run: |
        aws ecs update-service --cluster "WebApp_2" --service "web" --desired-count ${{ github.event.inputs.Capacity }}
        
    - name: Api
      run: |
        aws ecs update-service --cluster "WebApp_2" --service "api" --desired-count ${{ github.event.inputs.Capacity }}
  
        


          